# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/roland/Data/Source/imgui2/vsgimgui/src2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/roland/Data/Source/imgui2/vsgimgui/src2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roland/Data/Source/imgui2/vsgimgui/src2/CMakeFiles /home/roland/Data/Source/imgui2/vsgimgui/src2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roland/Data/Source/imgui2/vsgimgui/src2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vsgimgui

# Build rule for target.
vsgimgui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vsgimgui
.PHONY : vsgimgui

# fast build rule for target.
vsgimgui/fast:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/build
.PHONY : vsgimgui/fast

#=============================================================================
# Target rules for targets named clobber

# Build rule for target.
clobber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clobber
.PHONY : clobber

# fast build rule for target.
clobber/fast:
	$(MAKE) -f CMakeFiles/clobber.dir/build.make CMakeFiles/clobber.dir/build
.PHONY : clobber/fast

VSGImGui.o: VSGImGui.cpp.o

.PHONY : VSGImGui.o

# target to build an object file
VSGImGui.cpp.o:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/VSGImGui.cpp.o
.PHONY : VSGImGui.cpp.o

VSGImGui.i: VSGImGui.cpp.i

.PHONY : VSGImGui.i

# target to preprocess a source file
VSGImGui.cpp.i:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/VSGImGui.cpp.i
.PHONY : VSGImGui.cpp.i

VSGImGui.s: VSGImGui.cpp.s

.PHONY : VSGImGui.s

# target to generate assembly for a file
VSGImGui.cpp.s:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/VSGImGui.cpp.s
.PHONY : VSGImGui.cpp.s

VSGImGuiEventHandler.o: VSGImGuiEventHandler.cpp.o

.PHONY : VSGImGuiEventHandler.o

# target to build an object file
VSGImGuiEventHandler.cpp.o:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/VSGImGuiEventHandler.cpp.o
.PHONY : VSGImGuiEventHandler.cpp.o

VSGImGuiEventHandler.i: VSGImGuiEventHandler.cpp.i

.PHONY : VSGImGuiEventHandler.i

# target to preprocess a source file
VSGImGuiEventHandler.cpp.i:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/VSGImGuiEventHandler.cpp.i
.PHONY : VSGImGuiEventHandler.cpp.i

VSGImGuiEventHandler.s: VSGImGuiEventHandler.cpp.s

.PHONY : VSGImGuiEventHandler.s

# target to generate assembly for a file
VSGImGuiEventHandler.cpp.s:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/VSGImGuiEventHandler.cpp.s
.PHONY : VSGImGuiEventHandler.cpp.s

imgui/imgui.o: imgui/imgui.cpp.o

.PHONY : imgui/imgui.o

# target to build an object file
imgui/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui.cpp.o
.PHONY : imgui/imgui.cpp.o

imgui/imgui.i: imgui/imgui.cpp.i

.PHONY : imgui/imgui.i

# target to preprocess a source file
imgui/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui.cpp.i
.PHONY : imgui/imgui.cpp.i

imgui/imgui.s: imgui/imgui.cpp.s

.PHONY : imgui/imgui.s

# target to generate assembly for a file
imgui/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui.cpp.s
.PHONY : imgui/imgui.cpp.s

imgui/imgui_demo.o: imgui/imgui_demo.cpp.o

.PHONY : imgui/imgui_demo.o

# target to build an object file
imgui/imgui_demo.cpp.o:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.cpp.o

imgui/imgui_demo.i: imgui/imgui_demo.cpp.i

.PHONY : imgui/imgui_demo.i

# target to preprocess a source file
imgui/imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.cpp.i

imgui/imgui_demo.s: imgui/imgui_demo.cpp.s

.PHONY : imgui/imgui_demo.s

# target to generate assembly for a file
imgui/imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.cpp.s

imgui/imgui_draw.o: imgui/imgui_draw.cpp.o

.PHONY : imgui/imgui_draw.o

# target to build an object file
imgui/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.cpp.o

imgui/imgui_draw.i: imgui/imgui_draw.cpp.i

.PHONY : imgui/imgui_draw.i

# target to preprocess a source file
imgui/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.cpp.i

imgui/imgui_draw.s: imgui/imgui_draw.cpp.s

.PHONY : imgui/imgui_draw.s

# target to generate assembly for a file
imgui/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.cpp.s

imgui/imgui_impl_vulkan.o: imgui/imgui_impl_vulkan.cpp.o

.PHONY : imgui/imgui_impl_vulkan.o

# target to build an object file
imgui/imgui_impl_vulkan.cpp.o:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_impl_vulkan.cpp.o
.PHONY : imgui/imgui_impl_vulkan.cpp.o

imgui/imgui_impl_vulkan.i: imgui/imgui_impl_vulkan.cpp.i

.PHONY : imgui/imgui_impl_vulkan.i

# target to preprocess a source file
imgui/imgui_impl_vulkan.cpp.i:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_impl_vulkan.cpp.i
.PHONY : imgui/imgui_impl_vulkan.cpp.i

imgui/imgui_impl_vulkan.s: imgui/imgui_impl_vulkan.cpp.s

.PHONY : imgui/imgui_impl_vulkan.s

# target to generate assembly for a file
imgui/imgui_impl_vulkan.cpp.s:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_impl_vulkan.cpp.s
.PHONY : imgui/imgui_impl_vulkan.cpp.s

imgui/imgui_tables.o: imgui/imgui_tables.cpp.o

.PHONY : imgui/imgui_tables.o

# target to build an object file
imgui/imgui_tables.cpp.o:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.cpp.o

imgui/imgui_tables.i: imgui/imgui_tables.cpp.i

.PHONY : imgui/imgui_tables.i

# target to preprocess a source file
imgui/imgui_tables.cpp.i:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.cpp.i

imgui/imgui_tables.s: imgui/imgui_tables.cpp.s

.PHONY : imgui/imgui_tables.s

# target to generate assembly for a file
imgui/imgui_tables.cpp.s:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.cpp.s

imgui/imgui_widgets.o: imgui/imgui_widgets.cpp.o

.PHONY : imgui/imgui_widgets.o

# target to build an object file
imgui/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.cpp.o

imgui/imgui_widgets.i: imgui/imgui_widgets.cpp.i

.PHONY : imgui/imgui_widgets.i

# target to preprocess a source file
imgui/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.cpp.i

imgui/imgui_widgets.s: imgui/imgui_widgets.cpp.s

.PHONY : imgui/imgui_widgets.s

# target to generate assembly for a file
imgui/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/vsgimgui.dir/build.make CMakeFiles/vsgimgui.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... vsgimgui"
	@echo "... clobber"
	@echo "... VSGImGui.o"
	@echo "... VSGImGui.i"
	@echo "... VSGImGui.s"
	@echo "... VSGImGuiEventHandler.o"
	@echo "... VSGImGuiEventHandler.i"
	@echo "... VSGImGuiEventHandler.s"
	@echo "... imgui/imgui.o"
	@echo "... imgui/imgui.i"
	@echo "... imgui/imgui.s"
	@echo "... imgui/imgui_demo.o"
	@echo "... imgui/imgui_demo.i"
	@echo "... imgui/imgui_demo.s"
	@echo "... imgui/imgui_draw.o"
	@echo "... imgui/imgui_draw.i"
	@echo "... imgui/imgui_draw.s"
	@echo "... imgui/imgui_impl_vulkan.o"
	@echo "... imgui/imgui_impl_vulkan.i"
	@echo "... imgui/imgui_impl_vulkan.s"
	@echo "... imgui/imgui_tables.o"
	@echo "... imgui/imgui_tables.i"
	@echo "... imgui/imgui_tables.s"
	@echo "... imgui/imgui_widgets.o"
	@echo "... imgui/imgui_widgets.i"
	@echo "... imgui/imgui_widgets.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

